
tournament:
    path:     /tournament
    defaults: { _controller: CoreBundle:Tournament:tournament }

tournament_score:
    path:     /tournament_score/{idTourament}
    defaults: { _controller: CoreBundle:Default:tournamentScore }

app_upload:
    path:     /app_upload
    defaults: { _controller: CoreBundle:Default:mobileAppUpload }

app_download:
    path:     /app_download
    defaults: { _controller: CoreBundle:Default:mobileAppDownload }