
tournament:
    path:     /tournament
    defaults: { _controller: CoreBundle:Default:tournament }

app_upload:
    path:     /app_upload
    defaults: { _controller: CoreBundle:Default:mobileAppUpload }

app_download_view:
    path:     /app/download
    defaults: { _controller: CoreBundle:Default:mobileAppDownload }

app_download_action:
    path:     /app/dowload_action
    defaults: { _controller: CoreBundle:Default:appDownload }