
tournament:
    path:     /tournament
    defaults: { _controller: CoreBundle:Default:tournament }

app_upload:
    path:     /app_upload
    defaults: { _controller: CoreBundle:Default:mobileAppUpload }

app_download:
    path:     /app_download
    defaults: { _controller: CoreBundle:Default:mobileAppDownload }