
tournament:
    path:     /tournament
    defaults: { _controller: CoreBundle:Default:tournament }

scoreTournament:
    path:     /scores_tournament
    defaults: { _controller: CoreBundle:Default:scoreTournaments }

app_upload:
    path:     /app_upload
    defaults: { _controller: CoreBundle:Default:mobileAppUpload }

app_download:
    path:     /app_download
    defaults: { _controller: CoreBundle:Default:mobileAppDownload }