engines:
  duplication:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "src/*"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "app/*"
  - "web/*"
  - "phpunit.phar"
  - "**/Entity/*"