image: grafikart/gitlab-ci:php7

before_script:
- composer install

services:
- mysql

variables:
    MYSQL_DATABASE: contestmanager

test:
    script:
    - php phpunit.phar --bootstrap app\autoload.php --configuration app\phpunit.xml.dist