language: php
php:
  - "7.0"

services:
  - mysql

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install -n --no-interaction
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console doctrine:fixtures:load -n --env=test

script: php phpunit.phar --bootstrap app/autoload.php --configuration app/phpunit.xml.dist