core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

match:
    resource: "@MatchBundle/Controller/"
    type:     annotation
    prefix:   /

team:
    resource: "@TeamBundle/Controller/"
    type:     annotation
    prefix:   /

school:
    resource: "@SchoolBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
easy_admin_bundle:
    resource: "@CoreBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /