# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.school:
        class: CoreBundle\Admin\SchoolAdmin
        arguments: [~, SchoolBundle\Entity\School, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: School }
        calls:
            - [addChild, ['@admin.student', '@admin.group']]
    admin.student:
        class: CoreBundle\Admin\StudentAdmin
        arguments: [~, SchoolBundle\Entity\Student, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Student }
    admin.config:
        class: CoreBundle\Admin\ConfigAdmin
        arguments: [~, CoreBundle\Entity\Config, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Config }
    admin.team:
        class: CoreBundle\Admin\TeamAdmin
        arguments: [~, TeamBundle\Entity\Team, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Team }
        calls:
            - [addChild, ['@admin.student']]
    admin.group:
        class: CoreBundle\Admin\GroupAdmin
        arguments: [~, MatchBundle\Entity\GroupMatch, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Group }
        calls:
            - [addChild, ['@admin.team']]
    admin.user:
        class: CoreBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        calls:
            - [addChild, ['@admin.group']]
    admin.versus:
        class: CoreBundle\Admin\VersusAdmin
        arguments: [~, MatchBundle\Entity\Versus, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Match }